import type { Metadata } from "next";
import "./globals.css";
import FFoodProvider from "@/providers/FastFoodProvider";
import Sidebar from "@/components/sidebar/Sidebar";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "myapp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" bg-[#f4f4f4]">
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
