import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar/Sidebar";
import FFoodProvider from "@/providers/FastFoodProvider";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "myapp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <FFoodProvider>
          <Sidebar />
          {children}
        </FFoodProvider>
      </body>
    </html>
  );
}
